### ISSUE TITLE
unable to install package

### ISSUE THREAD

**Issue by nadygold** [thephpleague/plates#154] opened 2017-10-16 05:21 UTC
Hi.. 
unable to install package
composer require league/plates
or 
composer require league/plates:3.*

error : 
Problem 1
The requested package league/plates No version set(parsed as 1.0.0) is satisfiable by league/plates[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
Note: I am useing windows 7 platform

**Comment by pine3ree** [comment] 2017-10-26 11:56
Hello @nadygold,
I am not sure about the cause...everything works smoothly in Linux. Did You try with quotes:
```
composer require "league/plates:3.*"
```
and without a version number
```
composer require league/plates
```
?
The error message indicates the inability to parse the expression 3.* into a legitimate and existing version number.

**Comment by ragboyjr** [comment] 2017-11-10 18:22
@nadygold any word? can we close this?

**Comment by dev-nadeem** [comment] 2017-11-11 05:50
yes

**Comment by ragboyjr** [comment] 2017-11-11 05:58
Thanks!

**Closed by ragboyjr** 2017-11-11 05:58 UTC
