### ISSUE TITLE
Is possible to call predefined function from extension?

### ISSUE THREAD

**Issue by feryardiant** [thephpleague/plates#102] opened 2015-11-28 20:11 UTC
Hi @reinink,

Just noticed that I can't call predefined function from extension, e.g. `escape()` or  `e()`. Let say I try to create this extension

``` php
namespace App\Utils\Views;

use League\Plates\Engine;
use League\Plates\Extension\ExtensionInterface;

class HtmlExtension implements ExtensionInterface
{

    public function register(Engine $engine)
    {
        $engine->registerFunction('htmlAttr', [$this, 'htmlAttr']);
    }

    public function htmlAttr(array $attributes = [])
    {
        if (empty($attributes)) {
            return '';
        }

        $attrs = [];
        foreach ($attributes as $key => $val) {
            if (is_int($key)) {
                $attrs[] = $val;
            } else {
                $attrs[] = $key.'="'.$this->template->e($val).'"';
            }
        }

        return implode(' ', $attrs);
    }
}
```

and it's fail

```
The template function "e" was not found.
```

Did I miss something here?

Thanks

**Comment by ragboyjr** [comment] 2016-12-23 20:36
@feryardiant No, you didn't miss anything, escape is a protected function, you can't access it from the outside. Once/if #122 your issue would be resolved.

**Comment by ragboyjr** [comment] 2016-12-23 20:38
In fact this is a dupe of #82

**Comment by ragboyjr** [comment] 2016-12-23 20:38
We can probably close this @reinink

**Comment by ragboyjr** [comment] 2016-12-24 20:09
Closing because it is a duplicate of #82

**Closed by ragboyjr** 2016-12-24 20:09 UTC
Labels: duplicate

**Comment by feryardiant** [comment] 2016-12-24 20:19
@ragboyjr ah sorry. Looking forward #122 to be merged.

Thank you.
